### ISSUE TITLE
injection-tck example needs updates to work with Weld 5 (CDI 4)

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/injection-tck#19]
TCKProducers.java currently makes use of the @New annotation, which was removed as part of CDI 4.  If this TCK is to be used for testing with EE 10, it needs to be updated to remove the usage of this annotation.

Updating the Weld SE dependency to 5.x in example/pom.xml results in the following compilation failure, as one would expect:
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project jakarta.inject-tck-example: Compilation failure: Compilation failure:
[ERROR] /jakarta/jakarta.inject-tck-2.0.1/example/src/test/java/TCKProducers.java:[24,33] cannot find symbol
[ERROR]   symbol:   class New
[ERROR]   location: package jakarta.enterprise.inject
[ERROR] /jakarta/jakarta.inject-tck-2.0.1/example/src/test/java/TCKProducers.java:[49,39] cannot find symbol
[ERROR]   symbol:   class New
[ERROR]   location: class TCKProducers
[ERROR] /jakarta/jakarta.inject-tck-2.0.1/example/src/test/java/TCKProducers.java:[60,44] cannot find symbol
[ERROR]   symbol:   class New
[ERROR]   location: class TCKProducers
[ERROR] /jakarta/jakarta.inject-tck-2.0.1/example/src/test/java/TCKProducers.java:[80,42] cannot find symbol
[ERROR]   symbol:   class New
[ERROR]   location: class TCKProducers
[ERROR] /jakarta/jakarta.inject-tck-2.0.1/example/src/test/java/TCKProducers.java:[89,40] cannot find symbol
[ERROR]   symbol:   class New
[ERROR]   location: class TCKProducers

**Comment by starksm64** [comment]
Ok, I'll update the example to use the https://github.com/weld/core/tree/master/inject-tck-runner content as that is what Weld 5.0.0.x used to pass the injection TCK and create a new service release.

**Comment by brideck** [comment]
Excellent, thanks.  I knew this had to have been solved somewhere already, but I didn't know what Git repo to poke around in.

**Comment by starksm64** [comment]
The updated 2.0.2 TCK is available:
https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip
